name: Arul Portfolio

on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: ./arul-portfolio/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: ./arul-portfolio

      - name: Build Angular application
        run: npx ng build --base-href /portfolio/
        working-directory: ./arul-portfolio

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./arul-portfolio/dist/arul-portfolio/browser

  deploy:
    needs: build
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4